### PR TITLE
A basic spike that reveals how we reset service providers

### PR DESCRIPTION
**Pull request by fir3pho3nixx**
If we resolve IResetServiceProvider we could maybe call Reset() to get the ServiceProvider to rebuild itself. 

The massive assumption I am making here is the reference to the IServiceCollection is always the same. 

This is a spike only, please never merge.

### CODE REVIEW

**Comment by generik0** [comment]
This is great. But this test should do the reset. but it doesn't:
Should_not_be_able_to_resolve_application_types_that_are_cross_wired_to_service_collection_after_applicationBuilder_created

Are you sure it is good enough to reset the ServiceProvider. When does aspnetcore do the update.?
I think we should keep it simple and throw an exception

**Comment by generik0** [comment]
@fir3pho3nixx 
All controllers, taghelpers and views go though the FrameworkDependencyResolver right?
So we know the serviceProvider will be not null after first controller is resolved, correct?

**Comment by fir3pho3nixx** [comment]
> This is great. But this test should do the reset. but it doesn't: Should_not_be_able_to_resolve_application_types_that_are_cross_wired_to_service_collection_after_applicationBuilder_created

Exactly right, it tries to make that go away.

**Comment by fir3pho3nixx** [comment]
> Are you sure it is good enough to reset the ServiceProvider. When does aspnetcore do the update.?

It is all about timing. After configure services you are done or are you?

> I think we should keep it simple and throw an exception

You 100% sure? We might have a way of making this problem transient.

**Comment by generik0** [comment]
I did a really stupid test. I registered the servicecollection to the container and i registered the windsorcontainer to the container.
This ment in HomeController i could do this:

image

And it works. The reset works.
Looks like it is the ApplicationBuild(  in the uTests which needs rethinking

Lets do it.

Can i make the servicecollection extension etc (without all the refactoring) and create a new PR tomorrow?

**Comment by generik0** [comment]
@fir3pho3nixx closing so to clean up. Or should i say, remove the cleanup and focus on the true issee

**Comment by fir3pho3nixx** [comment]
Hold on, you should not have closed this PR. 

This was my spike PR! :)

Please refer to issue: https://github.com/fir3pho3nixx/Windsor/issues/14#issuecomment-381728005

**Comment by generik0** [comment]
@fir3pho3nixx OMG. I closed the wrong PR #13. Seriously my bad, to fast, inaccurate. will slow down...

**Pull request closed without merging**
